baseurl: https://repartee-per-se.com/
title: Repartee, per se
author: AR Domingo
copyright: Copyright © 2021, Andres Domingo; all rights reserved.
paginate: 10
theme: hugo-clarity
disqusShortname: ''
DefaultContentLanguage: en
taxonomies:
  category: categories
  series: series
  tag: tags
