---
title: The New Anomaly
author: AR Domingo
date: '2022-06-29'
slug: [the-new-anomaly]
categories:
  - Politics
tags:
  - Supreme Court
draft: no
toc: no
---


```{r main, message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(scales)
options(scipen=999)

state_pops <- read.csv("X:/OneDrive/02. Data/Demographic Data/State Population Data 2022.csv")

state_pops <- filter(state_pops, State != "Puerto Rico" & State != "District of Columbia")

glimpse(state_pops)


tot <- sum(state_pops$Pop2021)

bans <- c("Utah", "Idaho", "North Dakota", "South Dakota", "Wyoming", "Missouri", "Ohio","Kentucky", 
          "Tennessee", "Arkansas", "Mississippi", "Alabama", "Lousiana", "Oklahoma", "Texas", "Iowa",
          "Indiana", "West Virginia", "South Carolina", "Georgia", "Arizona", "Michigan", "Wisconsin",
          "Florida", "Montana", "Nebraska")
str(bans)
unique(bans)
#tot_banned <- filter(state_pops, State %in% bans) %>% sum(Pop2010)

banned_pops <- state_pops %>% filter(State %in% bans)

tot_banned <- sum(banned_pops$Pop2021)

avg_pop21 <- round(mean(state_pops$Pop2021), 0)
med_pop21 <- round(median(state_pops$Pop2021), 0)
#min(state_pops$Pop2021)

st_stats <- select(state_pops, c(State, Pop2021, Pop2010))
st_stats <- mutate(st_stats, Change = Pop2021 - Pop2010)
glimpse(st_stats)

filter(st_stats, Change < 0) %>% arrange(-Change)

pct_banned <- tot_banned / tot


med_states <- filter(st_stats, Pop2021 < median(st_stats$Pop2021))
#filter(med_states, State %in% bans)


mean_states <- filter(st_stats, Pop2021 < mean(st_stats$Pop2021))
#filter(mean_states, State %in% bans)



over_mean <- filter(st_stats, Pop2021 > mean(st_stats$Pop2021))
overmean_ban <- filter(over_mean, State %in% bans)

sum(overmean_ban$Pop2021)



texas_21 <- filter(state_pops, State == "Texas")

blw_avg <- filter(banned_pops, Pop2021 < mean(st_stats$Pop2021))
```



<center>
<h3> The Numbers Matter </h3>
</center>

<center>
The total population of the United States is *`r comma(tot)`*.  
<break>

The average population per state is *`r comma(avg_pop21)`*.  
<break>

The median population per state is *`r comma(med_pop21)`*.
<break>
</center>

<center>
<h3> The Enigma of Public Opinion </h3>
</center>

There are **`r length(bans)`** states that have or will ban abortion, some with exceptions for rape, incest, or the life of the mother.  These states are home to **`r comma(tot_banned)`** Americans, **`r percent(pct_banned)`** of the population.

In a NPR/PBS NewsHour/Marist National Poll^[https://maristpoll.marist.edu/polls/npr-pbs-newshour-marist-national-poll-the-overturning-of-roe-v-wade-june-2022/], **58%** of Americans oppose the Court's decision - **`r comma(tot * .58)` people**. 

This means that **`r comma(tot * .58 - tot_banned)` more American oppose** this outcome than even *live in those states in which it's now illegal*.  That's still **`r comma(round((tot * .58 - tot_banned) - (texas_21$Pop2021), 0))`** more than the entire population of Texas *(`r comma(texas_21$Pop2021)`)*, the most populous state with a ban.  The median population of the states with bans is **`r comma(median(banned_pops$Pop2021))`**; which means that, of the **26** states, **half** of them have populations less than even that excess over Texas, and **`r length(blw_avg$Pop2021)`** of them have populations less than the national average *(`r comma(avg_pop21)`)*.

There are those in the GOP who frequently remonstrate the tyranny of the Left, but the oversized weight of the minority that has developed is the very manifestation of tyranny.


<center>
<h3> The Weight of Age </h3>
</center>

To add insult to this injury, of the **330 million people in America, 211 million^[https://www.statista.com/statistics/241488/population-of-the-us-by-sex-and-age/] of them are under age 50**.  Therefore, **`r percent(211 / 330)`** of the population has lived with the right to reproductive freedom their entire lives.

Every Justice on the Supreme Court is over age 50 and arguably well beyond their reproductive interests. The audacity it takes to tell the vast majority of people in this country they suddenly no longer have a Constitutional right they were born with is astounding.  Not to mention the arrogance it takes to decide that **two** separate Courts were *"egregiously"* wrong. 

Couple this with one of the core notions of the majority opinion - that this issue is not deeply rooted in the history of this nation.  The obvious question becomes what the qualification of "deeply rooted" actually means. Despite the fact that this seems like a severely subjective requirement, let's concede for a moment that it is not deeply rooted.  Does not a full fifth the entire history of this nation not constitute something that is fairly rooted?  If not, the Civil Rights Act came less than a decade before *Roe*.  Is that monumental expansion of rights also not "deeply rooted" in our history?

It is, however, inarguably in our interest - again, **`r percent(211 / 330)`** of the population has had this as a Constitutional right for their entire lives (this author included).

<center>
<h3> The Audacity of Arrogance </h3>
</center>

The fact that *Roe* was overturned by the narrowest Court majority possible should itself be indicative of how erroneous and reckless a decision it is.  And while *Casey* was a plurality decision, *Roe* was an even stronger majority (7-2) than the Alito-led *Dobbs* decision (6-3 to uphold the Mississippi law, but only 5-4 to overturn *Roe v Wade*).

This arrogance came on display again a day following the *Dobbs* decision when the Court overturned the lower Court ruling on *NY State Rifle & Pistol Assc v. Bruen*, which was a unanimous decision in the 2nd Circuit prior to being heard by the Supreme Court.  This was a stronger majority (6-3) than *Dobbs*, but far from unanimous.

Perhaps the Supreme Court should set a new standard for stare decisis in which a decision can only be overturned by a majority at least as strong as the original ruling.  If this were the case, *Dobbs* would have required at least one more justice.

While efforts to "pack" the Court are likely to fail and not really worth pursuing, perhaps the Legislature can set this standard.  Is it possible to add this to the list of checks and balances in the United States government?  Can the Legislative Branch impose a rule on the Judicial Branch to make a matching majority a requirement to overturn a prior ruling?

Because we're now stacking minority rule on minority rule.  A Court largely comprised of Justices nominated by presidents who lost the popular vote and confirmed by a Republican-led Senate that routinely represents tens of millions fewer Americans than their counterparts in larger states, is now overturning decades old decisions made by stronger majorities than they garner in their decisions to do so.

That imbalance of power is untenable at best.


<break>
