---
title: Strange
author: AR Domingo
date: '2020-08-04'
slug: [respite-from-a-chaotic-world]
categories:
  - Sports
tags:
  - Baseball
  - MLB
---

<center>
### Respite from a Chaotic World
</center>



As phenomenally strange and difficult as 2020 has been, I've found a little slice of solace from somewhere I actually expected the opposite. Being a bit of a traditionalist, I thought I would get a sour taste from the changes made to the rules this MLB season.  I was wrong.  Strange things are happening in baseball games because of the the new rules, the unstable schedule, extra roster changes, etc.  Things that would almost never happen in a "regular" regular season...and it's glorious.  The other day, a starter gave up 4 runs and then loaded the bases with only one out in the top of the 1st - and he wasn't taken out.  That's not normal, and it's fascinating.  I realize baseball isn't exactly the most exciting sport to watch, but if you don't watch it much, I recommend taking in a game or two this year.  Because with all hope and effort there will never be a season like this again.<br>


So I admit that for this one, small respite from a chaotic world, strange is alright in my book.<br><br>