---
title: A Game of Arc-Seconds
author: AR Domingo
date: '2020-10-14'
slug: a-game-of-arc-seconds
categories:
  - MLB
tags:
  - Baseball
---

<center>
#### A Game of Arc-Seconds
</center>


The Dodgers have lost the first two games of the NLCS to the Braves. Two games that would have been, if not for playing in a “bubble”, played in Los Angeles at their home field. This isn’t exactly rare; home field winning percentage tends to be, like winning percentage in general in baseball, less assured than with the other major sports. So this happens - it’s not surprising, even though the Dodgers could easily be argued to have had the better season.
But home field advantage this season has been eroded across all the major sports, either by location or by the desolate stadiums, or both, as with “bubbles” without fans. However, baseball retains an integral part of its home field advantage when other sports do not. Of course, factors like the cascading roar of support from the crowd, familiarity of one’s own court, field, rink, etc., are important features of home field advantage; but these are byproducts of geography for the most part.

Baseball is unique among the major sports. In basketball, football, hockey - there is no home field advantage built directly into the parameters of the game itself. Baseball has this in the form of the opportunity of being on offense last. If you don't bat last, you've won. And if you bat last, then have a 'non-zero' chance of winning. Just a chance, no matter how slim. This has to be a clear advantage, if for no other reason than that you can just skip it at the end entirely if you are in the lead. But there are definitely other reasons.

However, the key is that baseball is a game of failure; and more failure, and more still. Arguably more failure than in the other sports. But a short series of successes, 2 or 3 (sometimes just one), can alter the entire complexion of a game, or a playoff series. If football is a game of inches, baseball is a game of arc seconds.  The angle of a grand salami and the angle of a bases-loaded, 2-out popup is literally an infinitesimal. It is a game where the margin between fulfillment and founder is razor thin.

The Dodgers know this. Listen, I like the Braves, they’re a great team…but it’s been ages since the Dodgers brought it home. So Blue Crew, I hope you bring it home like in the 80s.

