---
title: If it walks like a GOAT and talks like a GOAT...
author: AR Domingo
date: '2021-02-07'
slug: if-it-walks-like-a-goat
categories:
  - Sports
tags:
  - Football
  - NFL
---

<center>
#### ...it might be a GOAT
</center>

I've never liked Tom Brady much - I was biased, I had real faith in a Bledsoe comeback.  But he is still really good, and I realized that he could have retired at around 36 or 37 with a career that would have easily gotten him into the Hall of Fame.  He could have been inducted after the 5-year waiting period, then come out of retirement to play this season and now in this Super Bowl.

But that's not what happened.  He actually added another half decade of NFL-level abuse on that aging frame, still remaining exceedingly successful while doing it.  So whether I loathed him or merely disliked him, whether I thought him a cheater or not; whatever I've thought of him during his career, at some level none of that matters and it's just kind of one hell of a thing to be a witness to.
<br><br><br>
*Update on this* [*here*](https://repartee-per-se.netlify.app/post/no-it-really-might-be-a-goat/)

