[[main]]
  name = "Home"
  url = ""
  weight = -110

#[[main]]
#  name = "Archives"
#  url = "post/rich-content/"
#  weight = -109

[[main]]
name = "Featured"
  identifier = "Featured"
  weight = -109

[[main]]
  name = "Featured"
  identifier = "Featured"
  url = "featured/"

# Submenus are done this way: parent -> identifier
[[main]]
  name = "Social Links"
  identifier = "Social Links"
  weight = -108
[[main]]
  parent = "Links"
  name = "GitHub"
  url = "https://github.com/ardomingo/"
[[main]]
  parent = "Links"
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/andres-domingo-75682343/"
[[main]]
  parent = "Links"
  name = "Twitter"
  url = "https://twitter.com/andresrdomingo/"
  
[[main]]
  parent = "Links"
  name = "Facebook"
  url = "https://www.facebook.com/andy.domingo/"  

[[main]]
  name = "About"
  url = "about/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/#"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/#"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/#"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"