---
title: 20 Years and 6 Degrees
author: AR Domingo
date: '2021-09-11'
slug: 20-years-and-6-degrees
categories:
  - Philosophy
  - Politics
tags:
  - Politics
---



Twenty years later, it's a near certainty that we are all within 6 degrees of separation from one of the 2,977 Americans who tragically lost their lives this day.  

We have met perhaps a cousin of someone lost who now works in our company, a church member's granddaughter who never met her grandfather, someone's brother-in-law who fought in our unit when we proudly volunteered, a friend of a friend whose life was somehow directly touched by the life of someone lost that day.

Thousands of people felt that loss directly, and nothing can change that or make it hurt any less.  But we bear that loss as a nation as well, and today we can remember the unity their loss created and honor them rightly.  We can teach a new generation of the resilience of the American spirit and the strength we wield when united.

And if we remember, if we reflect upon the country we became after the loss of those 2,977 souls 20 years ago and live by that memory - their sacrifice might just save us anew.

"Let's Roll."