---
title: Free Will and Fair Will
author: AR Domingo
date: '2021-04-30'
slug: free-will-and-fair-will
categories:
  - Philosophy
tags: []
---


I think the idea of “Free Will” gets complicated by the existence of a Divinely-derived morality.  Because it often reduces to a binary question that is largely based on the opinion of the deity that inspired said morality.  Is this good, or is this bad, to the deity?   I don’t doubt that there may be a God that defines a universal moral truth, to be sure, most of humanity believes this to be true in some way.  But I’m not sure if our knowledge of, or even our belief that there is a God that expects us to behave in a certain way, is fully compatible with the idea of Free Will.

When you provide students with a few major ideas to focus on for a test as most good teachers do, they are entirely free to focus on anything else or nothing at all.  But it’s such an obvious failing if a student chooses to ignore the recommendation, with such an obvious consequence that, I would argue, it completely dispels the notion that there is any real “free” choice in the matter.  

The truest “free will” would be free of any knowledge of, or any perception of, frankly any consequence.  No outside expectation would influence your moral compass – just your own intellect, and the society in which you exist.  Not that there are no consequences – all the rules can still apply, we just couldn’t know anything about them, or even that they exist.
The Fairness of such a freedom would, however, range from extremely dubious to downright scandalous (which would certainly also put the morality of any deity issuing it into question).  So what we get instead is perhaps not entirely Free Will…but maybe it’s pretty fair.